name: spectrogram-segmentation
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - jupyter=1.0.0  # Jupyter system, including the notebook and the IPython kernel, all in one go.
  - numpy=1.26.*
  - pandas=2.2.*
  - matplotlib=3.8.*
  - scipy=1.11.*
  - scikit-learn=1.3.*
  - pillow=10.2.*
  - pytorch=2.2.*
  - pytorch-lightning=2.0.*
  - torchvision=0.15.*
  - torchmetrics=1.1.*
  - pyyaml=6.0.*
  - cffi=1.16.*
  - gdal=3.6.*

# Note: We use Conda for this example because it is the easiest way to install GDAL, which is required to read
#  the spectrogram masks from the spectrogram sensing dataset.
