name: spectrogram-segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter=1.0.*
  - matplotlib=3.4.*
  - numpy=1.26.*
  - pandas=1.3.*
  - scikit-learn=1.0.*
  - pytorch=1.10.*
  - torchvision=0.11.*
  - pillow=8.4.*
  - scipy=1.7.*
  - pyyaml=6.0.*
  - h5py=3.4.*
  - pyhdf=0.11.*
  - cffi=1.14.*
  - gdal=3.3.*
  - torchmetrics=0.5.*
  - pytorch-lightning=1.5.*
  - chardet=4.0.*
  - tensorboard=2.6.*
