name: spectrogram-segmentation
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.3.*
  - jupyter=1.0.0  # Jupyter system, including the notebook and the IPython kernel, all in one go.
  - numpy=1.26.*
  - pandas=2.2.*
  - matplotlib=3.8.*
  - scipy=1.11.*
  - scikit-learn=1.3.*
  - pillow=10.2.*
  - pytorch=2.3.*
  - pytorch-lightning=2.0.*
  - torchmetrics=1.1.*
  - gdal=3.6.*
  - pip:
    - torchvision==0.18.*

# Note: We use Conda for this example because it is the easiest way to install GDAL, which is required to read
#  the spectrogram masks from the spectrogram sensing dataset.
