[tool.black]
line-length = 119
target-version = ["py310"]
exclude = '''
    /(
          \.git
        | \.github
        | venv
        | \.venv
        | env
        | \.env
        | \.idea
        | \.vscode
        | \.ipynb_checkpoints
    )/
'''

[tool.isort]
profile = "black"
